config/routes.rb
Uploader::Application.routes.draw do
  resources :contents, :except => 'index' do
    member do
      get 'download'
    end
  end
  root 'contents#index'

  

end

app/models/content.rb
require 'bcrypt'

class Content < ActiveRecord::Base
  
  validates :upload_file, presence: { message: 'ファイルを選択してください'}

  before_save { self.password = BCrypt::Password.create(password) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: [:show, :edit, :update, :destroy, :download]

  # GET /contents
  # GET /contents.json
  def index
    @contents = Content.all
    @content = Content.new
  end

  # GET /contents/1
  # GET /contents/1.json
  def show
  end

  # GET /contents/new
  def new
    @content = Content.new
  end

  # GET /contents/1/edit
  def edit
  end

  # POST /contents
  # POST /contents.json
  def create
    upload_file = content_params[:upload_file]
    content = {}
    if upload_file != nil
      content[:upload_file] = upload_file.read
      content[:upload_file_name] = upload_file.original_filename
    end
    content[:password] = content_params[:password]
    @content = Content.new(content)
    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, notice: 'Upload success' }
        format.json { render action: 'show', status: :created, location: @content }
      else
        @contents = Content.all
        format.html { render action: 'index' }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contents/1
  # PATCH/PUT /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to @content, notice: 'Content was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    password = params[:password]

    hash_password = BCrypt::Password.new(@content.password)
    if hash_password == password
      @content.destroy
      respond_to do |format|
        format.html { redirect_to root_path, notice: "Delete success." }
        #format.html { redirect_to contents_url }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { 
          flash[:alert] = "Delete fail."
          render action: 'show'
        }
      end
    end
  end

  def download
    send_data(@content.upload_file, filename: @content.upload_file_name, type: "text/plain")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def content_params
      params.require(:content).permit(:upload_file_name, :upload_file, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_form.html.erb
<%= form_for(@content) do |f| %>
  <% if @content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
      <% @content.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :upload_file_name %><br>
    <%= f.text_field :upload_file_name %>
  </div>
  <div class="field">
    <%= f.label :upload_file %><br>
    <%= f.text_field :upload_file %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contents/edit.html.erb
<h1>Editing content</h1>

<%= render 'form' %>

<%= link_to 'Show', @content %> |
<%= link_to 'Back', contents_path %>

app/views/contents/index.html.erb
<h1>Uploader</h1>

<p id="notice"><%= notice %></p>

<% if @content.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@content.errors.count, "error") %> prohibited this content from being saved:</h2>

    <ul>
      <% @content.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(@content) do |f| %>
  <div class="field">
    <%= f.label :upload_file %>
    <%= f.file_field :upload_file %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit "Upload" %>
  </div>
<% end %>

<h2>Uploaded File</h2>
<ul>
  <% @contents.each do |content| %>
    <li><%= link_to content.upload_file_name, content_path(content) %></li>
  <% end %>
</ul>

app/views/contents/new.html.erb
<h1>New content</h1>

<%= render 'form' %>

<%= link_to 'Back', contents_path %>

app/views/contents/show.html.erb
<% flash.each do |key, value| %>
  <p id="<%= key %>"><%= value %></p>
<% end %>

<h2><%= @content.upload_file_name %></h2>

<p>
  <%= button_to "Download", download_content_path(@content), method: "get" %>
</p>

<%= form_tag(content_path(@content), :method => :delete) do %>
  <div class="field">
    <%= label_tag :password %>
    <%= password_field_tag :password %>
  </div>
  <div class="actions">
    <%= submit_tag "Delete" %>
  </div>
<% end %>

<%= link_to 'Back', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Uploader</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= yield %>

  <%= debug(params) if Rails.env.development? %>
</body>
</html>